# -*- coding: utf-8 -*-
"""Compressor.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1G-QoaV9YCKJhrybhYLWRyvPST3aXUQtA
"""

import os
from model import Autoencoder
from utils.training import *
import torchvision.transforms.functional as TF
import numpy as np
from PIL import Image
from utils.data.bitstring import *
import lzma
import zlib

file_name="IMG_20201114_172038.jpg"
filename,filextension=os.path.splitext(file_name)

new_file_name=filename+"_compressed"+filextension

class Encoder():
    def __init__(self, path):
        self.model = Autoencoder().float()
        self.model.eval()
        checkpoint = torch.load(path , map_location=torch.device('cpu'))
        self.model.load_state_dict(checkpoint['model_state'])

    def compress(self,path):
        img = Image.open(path)
        width, height = img.size
        dw = 32 - (width%32)
        dh = 32 - (height%32)
        img = TF.pad(img,(dw,dh,0,0))
        x =  TF.to_tensor(img)
        x = x.unsqueeze(0)
        x = self.model.enc(x)
        x = self.model.binarizer(x)
        
        y = x.cpu().detach().numpy()
        y[y<0] = 0
        y[y>0] = 1
        return y,dw,dh
    def encode_and_save(self, in_path, out_path):
        y,dw,dh = self.compress(in_path)
        comp_dw = BitArray(uint=dw,length=8)
        comp_dh = BitArray(uint=dh,length=8)
        comp_S2 = BitArray(uint=y.shape[2],length = 16)
        comp_S3 = BitArray(uint = y.shape[3],length=16)

        y = y.ravel()
        comp_y = BitArray(y)
        with lzma.open(out_path , 'wb', preset=9) as fp:
            fp.write(comp_dw.tobytes())
            fp.write(comp_dh.tobytes())
            fp.write(comp_S2.tobytes())
            fp.write(comp_S3.tobytes())
            fp.write(comp_y.tobytes())

encoder = Encoder("weight_file.tar")

encoder.encode_and_save(file_name ,new_file_name)